In [1]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([[10], [20], [30]])
result = x + y
print(result)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [2]:
x = np.array([[5, 6, 7, 8], [1, 2, 3, 4], [9, 10, 11, 12]])
y = np.array([1, 2, 3, 4])
result = x - y
print("2D Array x:\n", x)
print("1D Array y:\n", y)
print("Result of x - y:\n", result)

2D Array x:
 [[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
1D Array y:
 [1 2 3 4]
Result of x - y:
 [[4 4 4 4]
 [0 0 0 0]
 [8 8 8 8]]


In [3]:
a = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],

              [[13, 14, 15, 16],
               [17, 18, 19, 20],
               [21, 22, 23, 24]]])

b = np.array([2, 3, 4, 5])
result = a * b
print("3D Array a:\n", a)
print("1D Array b:\n", b)
print("Result of a * b:\n", result)

3D Array a:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
1D Array b:
 [2 3 4 5]
Result of a * b:
 [[[  2   6  12  20]
  [ 10  18  28  40]
  [ 18  30  44  60]]

 [[ 26  42  60  80]
  [ 34  54  76 100]
  [ 42  66  92 120]]]
