In [1]:
import numpy as np

In [2]:
x=np.arange(1,7).reshape(2,3)
y=np.arange(1,7).reshape(2,3)
print(x)
print(y)
r=np.dot(x, y.T)
print(r)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[14 32]
 [32 77]]


In [3]:
from numpy import linalg as LA
a = np.array([[1, 0], [1, 2]])
print("Original 2-d array")
print(a)
print("Determinant of the said 2-D array:")
print(np.linalg.det(a)) 

Original 2-d array
[[1 0]
 [1 2]]
Determinant of the said 2-D array:
2.0


In [4]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("Original matrices:")
print(p)
print(q)
result1 = np.cross(p, q)
result2 = np.cross(q, p)
print("Cross product of the said two vectors (p, q):")
print(result1)
print("Cross product of the said two vectors (q, p):")
print(result2) 

Original matrices:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Cross product of the said two vectors (p, q):
[ 2 -3]
Cross product of the said two vectors (q, p):
[-2  3]


C:\Users\HarshPatel\AppData\Local\Temp\ipykernel_2708\3053680182.py:6: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  result1 = np.cross(p, q)
C:\Users\HarshPatel\AppData\Local\Temp\ipykernel_2708\3053680182.py:7: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  result2 = np.cross(q, p)
