In [1]:
import numpy as np

In [2]:
x=np.arange(1,10).reshape(3,3)
print(x)

x=x.flatten()
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [3]:
max_val=np.max(x)
min_val=np.min(x)
print(max_val)
print(min_val)

9
1


In [4]:
x=np.arange(1,10).reshape(3,3)
print(x)

max_val=np.max(x,axis=1)
min_val=np.min(x,axis=1)
print(max_val)
print(min_val)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6 9]
[1 4 7]


In [5]:
r=np.ptp(x,axis=1)
print(r)

[2 2 2]
