In [1]:
import numpy as np

In [2]:
x=np.array([[10,40],[30,20],[50,90]])
print(x)

[[10 40]
 [30 20]
 [50 90]]


In [3]:
np.sort(x,axis=0)

array([[10, 20],
       [30, 40],
       [50, 90]])

In [4]:
np.sort(x,axis=1)

array([[10, 40],
       [20, 30],
       [50, 90]])

In [5]:
data_type = [('name', 'U10'), ('class', int), ('height', float)]
students_details = [('Harsh', 5, 48.5), ('Piyush', 6, 52.5), ('Dhyan', 5, 42.10), ('Daiwik', 5, 40.11)]
students = np.array(students_details, dtype=data_type)
print("Original array:")
print(students)
print("Sort by height")
print(np.sort(students, order='height'))   

Original array:
[('Harsh', 5, 48.5 ) ('Piyush', 6, 52.5 ) ('Dhyan', 5, 42.1 )
 ('Daiwik', 5, 40.11)]
Sort by height
[('Daiwik', 5, 40.11) ('Dhyan', 5, 42.1 ) ('Harsh', 5, 48.5 )
 ('Piyush', 6, 52.5 )]


In [6]:
data_type = [('name', 'U10'), ('class', int), ('height', float)]
students_details = [('Harsh', 5, 48.5), ('Piyush', 6, 52.5), ('Dhyan', 5, 42.10), ('Daiwik', 6, 40.11)]
students = np.array(students_details, dtype=data_type)
print("Original array:")
print(students)
print("Sort by class")
print(np.sort(students, order=['class', 'height']))   

Original array:
[('Harsh', 5, 48.5 ) ('Piyush', 6, 52.5 ) ('Dhyan', 5, 42.1 )
 ('Daiwik', 6, 40.11)]
Sort by class
[('Dhyan', 5, 42.1 ) ('Harsh', 5, 48.5 ) ('Daiwik', 6, 40.11)
 ('Piyush', 6, 52.5 )]
