In [1]:
import numpy as np

In [2]:
a=np.random.randint(0,100,size=(5,5))
val=50
print(a)
elements=a[a>val]
print(elements)

[[65 35 79  0 84]
 [12 70 70 81 29]
 [29 13 27 47 98]
 [36 16 58 77 80]
 [81 56 81 24 96]]
[65 79 84 70 70 81 98 58 77 80 81 56 81 96]


In [3]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
index = np.array([0, 2, 4, 6, 8])
elements = a[index]
print(a)
print('Index array:\n', index)
print('Selected elements:\n', elements)

[ 10  20  30  40  50  60  70  80  90 100]
Index array:
 [0 2 4 6 8]
Selected elements:
 [10 30 50 70 90]
