In [1]:
import numpy as np

In [2]:
x = np.random.normal(size=5)
print(x) 

[ 1.42359358  2.16943539 -0.03793112 -0.36359817  0.59738216]


In [3]:
x = np.random.randint(low=10, high=30, size=6)
print(x) 

[26 20 28 23 11 26]


In [4]:
x = np.random.random((3, 3, 3))
print(x) 

[[[0.40252597 0.20078477 0.2655085 ]
  [0.30243033 0.06697689 0.84999527]
  [0.93178284 0.76300846 0.89795595]]

 [[0.93944807 0.49617074 0.0297134 ]
  [0.91228171 0.8921086  0.8953219 ]
  [0.6586622  0.4030966  0.0555916 ]]

 [[0.35155063 0.56492646 0.69351048]
  [0.99148252 0.33402059 0.06332658]
  [0.11093994 0.05663242 0.97365213]]]
