In [1]:
import numpy as np
def add_ten(x):
    return x + 10
add_ten_ufunc = np.frompyfunc(add_ten, 1, 1)
array_1d = np.array([1, 2, 3, 4, 5])
result_array = add_ten_ufunc(array_1d)
print('Original 1D array:', array_1d)
print('Resulting array after applying add_ten_ufunc:', result_array)

Original 1D array: [1 2 3 4 5]
Resulting array after applying add_ten_ufunc: [11 12 13 14 15]


In [2]:
array_2d = np.random.randint(1, 100, size=(3, 3))
sqrt_array = np.sqrt(array_2d)
print('Original 2D array:\n', array_2d)
print('Square root of each element:\n', sqrt_array)

Original 2D array:
 [[32 26 33]
 [63 39 44]
 [ 2 43 20]]
Square root of each element:
 [[5.65685425 5.09901951 5.74456265]
 [7.93725393 6.244998   6.63324958]
 [1.41421356 6.55743852 4.47213595]]


In [3]:
array_2d = np.random.randint(0, 10, size=(3, 3))
array_1d = np.random.randint(0, 10, size=3)
result_array = np.add(array_2d, array_1d)
print('Original 2D array:\n', array_2d)
print('1D array:\n', array_1d)
print('Resulting array after adding 1D array to each row of 2D array:\n', result_array)

Original 2D array:
 [[1 4 7]
 [3 1 3]
 [5 8 0]]
1D array:
 [3 8 0]
Resulting array after adding 1D array to each row of 2D array:
 [[ 4 12  7]
 [ 6  9  3]
 [ 8 16  0]]
