In [1]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.vstack((arr1, arr2))
print(stacked_arr)

[[1 2 3]
 [4 5 6]]


In [2]:
arr = np.array([1, 2, 3, 4, 5])
exponential_arr = np.exp(arr)
print(exponential_arr)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [3]:
matrix = np.random.random((4, 3))
column_means = np.mean(matrix, axis=0)
print(column_means)

[0.46664907 0.45009035 0.26299397]


In [4]:
matrix = np.random.random((3, 4))
max_value_index = np.unravel_index(np.argmax(matrix), matrix.shape)
min_value = np.min(matrix)
matrix[max_value_index] = min_value
print(matrix)

[[0.7485413  0.45518898 0.11137333 0.64882164]
 [0.28231471 0.79227945 0.02338643 0.02338643]
 [0.74105632 0.65049086 0.68730461 0.5258152 ]]


In [5]:
matrix = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])
row_means_ignore_nan = np.nanmean(matrix, axis=1)
print(row_means_ignore_nan)

[1.5 5.  8. ]
