In [1]:
import numpy as np
nums1 = np.array([[1, 2], [3, 4], [5, 6]])
nums2 = np.array([7, 8])
print("Original arrays:")
print(nums1)
print(nums2)
result = np.dot(nums1, nums2)
print("Dot product of the said two arrays:")
print(result)

Original arrays:
[[1 2]
 [3 4]
 [5 6]]
[7 8]
Dot product of the said two arrays:
[23 53 83]


In [2]:
import numpy as np
matrix = np.identity(3)
print("3x3 identity matrix:")
print(matrix)
vert_stack = np.vstack((matrix, matrix, matrix))
horz_stack = np.hstack((matrix, matrix, matrix))
print("Vertical Stack:\n", vert_stack)
print("Horizontal Stack:\n", horz_stack)

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Vertical Stack:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Horizontal Stack:
 [[1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]]


In [3]:
import numpy as np
arr = np.random.rand(4, 4)
row_sum = np.sum(arr, axis=1)
print("Original array:")
print(arr)
print("\nSum of each row:")
print(row_sum)

Original array:
[[0.96655744 0.49949257 0.05580157 0.75527885]
 [0.07132668 0.19444977 0.33222647 0.72200448]
 [0.06888897 0.75934189 0.29375496 0.09198707]
 [0.88140637 0.57563023 0.75073961 0.77207194]]

Sum of each row:
[2.27713043 1.32000741 1.2139729  2.97984815]


In [4]:
import numpy as np
arr = np.random.rand(3, 3)
print("Original array elements:")
print(arr)
row_means = np.mean(arr, axis=1, keepdims=True)
print("\nMean of each row:")
print(row_means)
arr_subtracted = arr - row_means
print("\nSubtract the mean of each row from each element:")
print(arr_subtracted)

Original array elements:
[[0.70469105 0.98884064 0.04140207]
 [0.3299288  0.53408005 0.84158152]
 [0.24595763 0.24775971 0.79160945]]

Mean of each row:
[[0.57831125]
 [0.56853012]
 [0.42844227]]

Subtract the mean of each row from each element:
[[ 0.12637979  0.41052939 -0.53690918]
 [-0.23860132 -0.03445007  0.27305139]
 [-0.18248463 -0.18068255  0.36316718]]
