In [1]:
import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
arr = np.arange(10).reshape(2, -1)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
mat1 = np.random.random((5, 3))
mat2 = np.random.random((3, 2))
result = np.dot(mat1, mat2)
print(result)

[[0.5943696  0.32052522]
 [0.2657315  0.13743817]
 [0.84542958 0.61872405]
 [0.52502274 0.29586575]
 [0.52319605 0.22579974]]


In [4]:
arr = np.arange(1, 11)
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]


In [5]:
arr = np.arange(1, 10)
arr[arr % 2 != 0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1]


In [6]:
arr = np.array([-1, 2, 0, -4, 5])
boolean_arr = arr > 0
print(boolean_arr)

[False  True False False  True]


In [7]:
arr = np.arange(1, 10)
arr[arr % 2 == 0] *= -1
print(arr)

[ 1 -2  3 -4  5 -6  7 -8  9]


In [8]:
matrix = np.random.random((3,3))
normalized_matrix = (matrix - np.mean(matrix)) / np.std(matrix)
print(normalized_matrix)

[[-1.30323045  0.31977018 -0.82085878]
 [ 1.10007632  1.27025649  1.40279653]
 [-0.37492832 -1.19891712 -0.39496485]]


In [9]:
matrix = np.random.random((3, 3))
diagonal_sum = np.trace(matrix)
print(diagonal_sum)

0.8818573796660568


In [10]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)

(array([0, 1, 4]),)


In [11]:
arr = np.arange(10)
reversed_arr = np.flip(arr)
print(reversed_arr)

[9 8 7 6 5 4 3 2 1 0]


In [12]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
