In [1]:
list=[12.23, 13.32, 100, 36.32]

In [2]:
import numpy as np

In [3]:
x=np.array(list)

In [4]:
print(x)

[ 12.23  13.32 100.    36.32]


In [5]:
x=np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [6]:
x=np.zeros(10)

In [7]:
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
x[5]=11
print(x)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [9]:
x=np.arange(12,38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [10]:
x=x[::-1]
print(x)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [11]:
x=np.arange(1,5)
print(x)

x = x.astype(float)
print(x)

[1 2 3 4]
[1. 2. 3. 4.]
