In [1]:
import numpy as np
large_array = np.random.rand(1000000)
def sum_using_loop(array):
    total = 0.0
    for element in array:
        total += element
    return total
sum_loop = sum_using_loop(large_array)
print("Sum using for loop:", sum_loop)
sum_numpy = np.sum(large_array)
print("Sum using NumPy's built-in function:", sum_numpy)

Sum using for loop: 500172.38054716965
Sum using NumPy's built-in function: 500172.38054718403


In [2]:
array1 = np.random.rand(1000000)
array2 = np.random.rand(1000000)
def add_using_loop(arr1, arr2):
    result = np.zeros_like(arr1)
    for i in range(len(arr1)):
        result[i] = arr1[i] + arr2[i]
    return result
sum_loop = add_using_loop(array1, array2)
print("Sum using for loop (first 10 elements):", sum_loop[:10])
sum_vectorized = array1 + array2
print("Sum using vectorized operations (first 10 elements):", sum_vectorized[:10])

Sum using for loop (first 10 elements): [0.73739464 1.38680084 1.07258782 1.65614138 0.25163272 0.84162502
 1.26040849 1.00470195 0.94215554 1.0972452 ]
Sum using vectorized operations (first 10 elements): [0.73739464 1.38680084 1.07258782 1.65614138 0.25163272 0.84162502
 1.26040849 1.00470195 0.94215554 1.0972452 ]


In [3]:
array1 = np.random.rand(100, 100)
array2 = np.random.rand(100, 100)
def dot_product_using_loops(arr1, arr2):
    result = np.zeros((arr1.shape[0], arr2.shape[1]))
    for i in range(arr1.shape[0]):
        for j in range(arr2.shape[1]):
            for k in range(arr1.shape[1]):
                result[i, j] += arr1[i, k] * arr2[k, j]
    return result
dot_product_loops = dot_product_using_loops(array1, array2)
print("Dot product using nested for loops (first 5x5 block):\n", dot_product_loops[:5, :5])
dot_product_numpy = np.dot(array1, array2)
print("Dot product using NumPy's dot() function (first 5x5 block):\n", dot_product_numpy[:5, :5])

Dot product using nested for loops (first 5x5 block):
 [[24.07888469 24.48100369 22.99026045 31.30714673 25.83941874]
 [22.60544475 24.21675177 22.11646303 31.96734102 25.98925748]
 [24.80071616 26.04937729 22.31801754 31.30384976 25.56251129]
 [22.25261079 24.15999111 20.95480251 27.04563702 23.90075195]
 [21.33174681 22.90010724 20.26388656 27.07707498 23.47655227]]
Dot product using NumPy's dot() function (first 5x5 block):
 [[24.07888469 24.48100369 22.99026045 31.30714673 25.83941874]
 [22.60544475 24.21675177 22.11646303 31.96734102 25.98925748]
 [24.80071616 26.04937729 22.31801754 31.30384976 25.56251129]
 [22.25261079 24.15999111 20.95480251 27.04563702 23.90075195]
 [21.33174681 22.90010724 20.26388656 27.07707498 23.47655227]]
