In [1]:
import numpy as np
python_list = [1, 2, 3, 4, 5]
print("Original array:",python_list)
print("Type:",type(python_list))
numpy_array = np.array(python_list)
print("Python list to a NumPy array:")
print(numpy_array)
print("Type:",type(numpy_array))

Original array: [1, 2, 3, 4, 5]
Type: <class 'list'>
Python list to a NumPy array:
[1 2 3 4 5]
Type: <class 'numpy.ndarray'>


In [2]:
import numpy as np
numpy_array = np.array([1, 2, 3, 4, 5])
print("Original NumPy array:",numpy_array)
print("Type:",type(numpy_array))
python_list = numpy_array.tolist()
print("\nNumPy array to a Python list:")
print(python_list)
print("Type:",type(python_list))

Original NumPy array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>

NumPy array to a Python list:
[1, 2, 3, 4, 5]
Type: <class 'list'>


In [3]:
import pandas as pd
data = {'A': [1, 2, 3, 4, 5],
        'B': [10, 20, 30, 40, 50],
        'C': [100, 200, 300, 400, 500]}
df = pd.DataFrame(data)

print("Original Pandas DataFrame:",df)
print("Type:",type(df))
numpy_array = df.to_numpy()
print("\nPandas DataFrame to a NumPy array:")
print(numpy_array)
print("Type:",type(numpy_array))

Original Pandas DataFrame:    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500
Type: <class 'pandas.core.frame.DataFrame'>

Pandas DataFrame to a NumPy array:
[[  1  10 100]
 [  2  20 200]
 [  3  30 300]
 [  4  40 400]
 [  5  50 500]]
Type: <class 'numpy.ndarray'>


In [4]:
numpy_array = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

print("Original NumPy array:",numpy_array)
print("Type:",type(numpy_array))

df = pd.DataFrame(numpy_array, columns=['Column1', 'Column2', 'Column3'])
print("\nNumPy array to a Pandas DataFrame:")
print(df)
print(type(df))

Original NumPy array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Type: <class 'numpy.ndarray'>

NumPy array to a Pandas DataFrame:
   Column1  Column2  Column3
0        1        2        3
1        4        5        6
2        7        8        9
<class 'pandas.core.frame.DataFrame'>
