In [1]:
import numpy as np
import csv
csv_file_path = 'data.csv'
data_list = []
with open(csv_file_path, newline='') as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    for row in reader:
        numeric_row = []
        for element in row:
            try:
                numeric_value = float(element)
                numeric_row.append(numeric_value)
            except ValueError:
                continue
        if numeric_row:
            data_list.append(numeric_row)
data_array = np.array(data_list, dtype=object)
print(data_array)

[[10.0 12.0 95.0]
 [11.0 13.0 90.0]
 [12.0 34.0 85.0]
 [13.0 21.0 96.0]
 [14.0 55.0 95.0]]


In [2]:
data_array = np.array([
    [1, 'Harsh Patel', 95.5],
    [2, 'Dhyan Shah', 90.0],
    [3, 'Daiwik Korat', 80.0],
    [4, 'Piyush Chunara', 91.5]
], dtype=object)
csv_file_path = 'output.csv'
with open(csv_file_path, 'w', newline='') as csvfile:
    writer = csv.writer(csvfile, delimiter=',')
    for row in data_array:
        writer.writerow(row)
print(f"Data has been written to {csv_file_path}")

Data has been written to output.csv


In [3]:
csv_file_path = 'output.csv'
dtype = [('ID', 'i4'), ('Name', 'U15'), ('Score', 'f4')]
structured_array = np.genfromtxt(csv_file_path, delimiter=',', dtype=dtype, names=True)
print(structured_array)

[(2, 'Dhyan Shah', 90. ) (3, 'Daiwik Korat', 80. )
 (4, 'Piyush Chunara', 91.5)]
